### ISSUE TITLE
powerline_precmd -help does not output to screen

### ISSUE THREAD

**Issue by tomioueda** [justjanne/powerline-go#107]
When I do `powerline_precmd -help`, I do not get any output on the screen. 

Not sure if this is related but it also appears that the output of ` ~/go/bin/powerline-go -error $? -shell zsh` as well as `~/go/bin/powerline-go -error $?` produces gibberish in its output. Is that right? Screenshot below. 
![screen shot 2018-10-23 at 8 31 46 am](https://user-images.githubusercontent.com/14283332/47372384-7f141700-d69e-11e8-86d1-9b15d0d01443.png)

**Comment by tomioueda** [comment]
On a sidenote -- why does the documentation say to use `powerline-go -help` when the zsh config say to use `powerline_precmd`?

**Comment by justjanne** [comment]
ZSH requires a custom function to wrap the actual command, which is why we use powerline_precmd.

ZSH also parses the $PS1 content different from how it displays normal shell commands’ results, which is why "-shell zsh" results in apparent gibberish – it’s intended for $PS1, not for usage in normal commands.
