### ISSUE TITLE
Is it possible to use other themes?

### ISSUE THREAD

**Issue by mhnavarro** [justjanne/powerline-go#15]
If at this moment the answer is no, what is needed to make this possible?

**Comment by justjanne** [comment]
Currently there are two themes, "default" by me, and "low-contrast" by @autarch . You can contribute more themes yourself, or just edit the defaults.go file for this.

**Comment by autarch** [comment]
Ultimately, I wonder if it'd make sense to move this and some other bits to a config file? As it stands now, most changes require one or both of editing code and/or changing my `.bash_profile` and spawning a new shell. It'd be nice to be able to control more of powerline without having to do either. My initial thought would be to suggest json, purely because it's well-supported by the golang core.

That said, this obviously introduces more complexity to the code, since now you have to handle config from the CLI and a config file, resolving conflicts, etc.

**Comment by justjanne** [comment]
Complexity isn’t the issue, but performance. Reading and parsing JSON would double the latency again, and cause the prompt to be much slower again.

That’s why I prefer the solution via environment variables and arguments.

**Comment by autarch** [comment]
Here's another idea. If there were a config file, there could be a separate program that read the config and turned it into env vars. Then this could be executed in a shell's profile file once, rather than every time the shell prompt is needed.

**Comment by justjanne** [comment]
That could certainly work, but would require spawning a new shell to change things, too.

We could certainly try parsing Json, but we’d have to first measure the performance impact (depending on size of the file it might not be all too bad)
