### ISSUE TITLE
jobs segment not working in bash

### ISSUE THREAD

**Issue by cjvaughter** [justjanne/powerline-go#249]
I notice that bash is a special case where instead of using the parent pid, we use the parent's parent. I don't think this is correct, unless maybe an older version of bash worked differently... I'm on 5.0.17.

As a test, I started some jobs and then started another instance of bash, and sure enough it shows the parent's jobs.

![image](https://user-images.githubusercontent.com/12523019/98146546-3f898380-1e91-11eb-964c-202c88fca7f1.png)

**Comment by scop** [comment]
I can confirm that the current code does not work in bash 5.0.0 or 5.1-rc3, but does work with 4.4.20 and 3.2.57 (all on Ubuntu 18).

**Comment by awiddersheim** [comment]
Some additional context can be found in https://github.com/justjanne/powerline-go/pull/76 which may help as to how things ended up this way.

**Comment by scop** [comment]
In this test case with bash 4.4, `4576` is the one we're interested in:
```
28448 pts/34   Ss     0:35  |   \_ bash
 4576 pts/34   S+     0:34  |       \_ bash -i
 5138 pts/34   Rl     0:00  |           \_ emacs
 5193 pts/34   S+     0:00  |           \_ bash -i
 5194 pts/34   Sl+    0:00  |               \_ powerline-go -modules [...]
 5201 pts/34   R+     0:00  |                   \_ ps fax
```

With bash 5.0.0, `31110` is the one in this case:
```
28448 pts/34   Ss     0:00  |   \_ bash
31110 pts/34   S+     0:02  |       \_ bash -i
 4042 pts/34   Sl     0:01  |           \_ emacs
 4245 pts/34   Sl+    0:00  |           \_ powerline-go -modules [...]
 4252 pts/34   R+     0:00  |               \_ ps fax
```

Modded powerline-go to do and output `ps fax`. `emacs` is just a canary job there.

So, I suppose we could look into the process group id instead of the parent, maybe that'd work everywhere (well no idea about Windows), with all shells? Confirmed that just changing both `-oppid=`s to `-opgid=` in the original code makes it work with all bash versions here, didn't try any other shells but I guess they wouldn't be broken as long as the pgid functionality is there in the first place.

**Comment by scop** [comment]
Aside, as noted in #250, there are `ps` incompatibilities to deal with, and the current codepath for bash is broken at least with busybox 1.27.2 `ps`. Working with something like https://github.com/mitchellh/go-ps/blob/ddafa7589c607e0e81a7436520ccdbac913665a2/process_unix.go#L14 instead should elide those issues. Don't know about Windows.
