### ISSUE TITLE
Prompt does not shrink when -max-width is specfied

### ISSUE THREAD

**Issue by fenprace** [justjanne/powerline-go#279]
**Describe the bug**
Prompt does not shrink for a given -max-width value.
 
**To Reproduce**
1. `powerline-go -max-width 50`

<img width="785" alt="截屏2021-01-22 23 37 01" src="https://user-images.githubusercontent.com/968767/105491797-02ec5c00-5d0b-11eb-9428-a3b01ae1cc5e.png">

**Expected behavior**
Expect 1 or 2 segments are hidden and the printed out prompt takes no more than 50% of the width of the window.

**Environment**
 - OS: macOS 11.1
 - Architecture: x86_64
 - Shell: fish 3.1.2

**Additional context**
My prompt settings are as following. But the `-max-width` does not work in prompt either.

```fish
function fish_prompt
  powerline-go -error $status -modules cwd,git,root -cwd-mode dironly -max-width 50
end
```

**Comment by scottslowe** [comment]
I can confirm this same behavior with `powerline-go` 1.20.0 on Fedora 33, with Bash as the shell.

**Comment by rpadaki** [comment]
Update: The issue seems to be from PR #251, which mistakenly assumes that the flag [`-max-width`](https://github.com/justjanne/powerline-go/blob/master/args.go#L140) is instead [`max-width-percentage`](https://github.com/justjanne/powerline-go/blob/master/main.go#L168).

I have the fix working locally, and I'm about to open up a pull request fixing this! (Which will be linked below)
